### ISSUE TITLE
[Question] Is it possible t have multiple tagets for one out connector?

### ISSUE THREAD

**Issue by AndreasGeorg** [miroiu/nodify#129]
At first thanks for your great work.
If try to write an application to visiualize some automation blocks. There it is common to connect a out parameter to several input parameters.
Thate look like this:
```
block1.out_1 --> block2.in_1
block1.out_1 --> block2.in_2
block1.out_1 --> block2.in_3
block2.in_1   --> block3.in_1
block2.out_1 --> block3.in_2
```

**Comment by miroiu** [comment]
Hi, you can have as many targets as you want. The library only provides the UI, not the business rules. I suggest you try out the example applications because there are examples of how you can set up business rules.

![image](https://github.com/user-attachments/assets/4bf7e788-cca6-43a8-9879-beed516fb96e)

**Comment by AndreasGeorg** [comment]
Thank you, sorry I haven't seen that before.
