### ISSUE TITLE
[Question] How do you make Connection in Notify more clickable range?

### ISSUE THREAD

**Issue by lyq-lin** [miroiu/nodify#131]
Hello, @miroiu . I'd like to make the Connection clickable wider in Notify. In other words, the range that can be clicked is larger than what is actually seen, is there a chance that it will be realized? I would appreciate it if you could provide ideas!

ex:
![image](https://github.com/user-attachments/assets/8295f194-0261-49fd-b69c-8c89728a3549)

I've noticed that Connection in Notify has an animation that expands when selected. It might look something like this, but I need to broaden the range before I select, or rather, expand the range of options.

**Comment by miroiu** [comment]
Hi @lyq-lin , I would like to implement this for the next release, but I can't do it before the second half of this month. The solution I'm thinking of is to draw the connection wire a second time but with a larger stroke thickness and a transparent brush. This will be configurable because not all projects need to interact with connection wires, and it may also decrease performance.

**Comment by lyq-lin** [comment]
> Hi @lyq-lin , I would like to implement this for the next release, but I can't do it before the second half of this month. The solution I'm thinking of is to draw the connection wire a second time but with a larger stroke thickness and a transparent brush. This will be configurable because not all projects need to interact with connection wires, and it may also decrease performance.

Maybe I should implement this section in OnRender, thanks for your help!

**Comment by miroiu** [comment]
I created a PR to address this issue. #133
