### ISSUE TITLE
[Question] NodifyObservableCollection Move()

### ISSUE THREAD

**Issue by GGorany** [miroiu/nodify#21]
When Changing the order of nodes in real time using Move() of NodifyObservableCollection,
Connection is not properly connected.

![Animation](https://user-images.githubusercontent.com/43957958/124869652-76093680-dffc-11eb-9efc-aae1ef66b4bc.gif)

Please, Check this.
Thank you very much.

**Comment by miroiu** [comment]
Hi,
This is the default behavior of [ObservableCollection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1.move?view=net-5.0). `Move` does not swap items but replaces them.

I would suggest that you add an `Order` dependency property on the `NodeViewModel` and bind it to the drop-down to keep track of the order of the nodes if that's what you're trying to do.

Otherwise, you will end up with more bugs when you remove or add nodes.

**Comment by GGorany** [comment]
I decided not to change the order of the nodes using Move() as per your advice.

It was not easy to change the execution order of the nodes.

Thank you very much for your advice.
