### ISSUE TITLE
[Question] StartedCommand CanExecute is not working

### ISSUE THREAD

**Issue by trrahul** [miroiu/nodify#58]
Hi @miroiu. I am trying to restrict a connector to having only one outgoing connection by checking if it is already connected and returning a false from CanExecute.

`StartConnectionCommand = new RelayCommand<ConnectorViewModel>(source => PendingConnection.Source = source!, model => !model.IsConnected);`

But this is not working. Am I doing it the correct way?

**Comment by miroiu** [comment]
Hi @trrahul ! The recommended method is to create or cancel the pending connection in the `PendingConnection.CompletedCommand` command handler. Because even if you don't start the connection from the "disabled" connector, you can still drop pending connections onto it.

In support of the recommended approach, there is the `EnablePreview` dependency property that works with a `PreviewTarget`, which you can use to show the connection status in real time. (pay attention to the tooltip text below)

![connect](https://user-images.githubusercontent.com/12727904/230853963-2c2f4aff-2c79-4357-a8b1-df193fc0d19f.gif)

However, you have a good point! Users should not be able to start a pending connection if that's not allowed.

**Comment by miroiu** [comment]
This is now fixed, and it can be seen in the `Calculator` example app. Please let me know if that's what you wanted to achieve.

**Comment by trrahul** [comment]
Yes, working as expected. Thanks!
